### PR TITLE
Feature/clang format

### PR DESCRIPTION
**Pull request by HiveBeats**
I've formatted all files as well, to pass the check.

### CODE REVIEW

**Comment by HiveBeats** [comment]
#3

**Comment by blitz** [comment]
Really nice! Thanks for taking this up. Can you rebase on top of master? I'll merge it then.

**Comment by HiveBeats** [comment]
@blitz Please check if i did it correctly 👍

**Review by blitz — APPROVED** [review]

**Comment by blitz** [comment]
Thanks again! Sorry for the slow turnaround time. This is definitely super appreciated. :heart:

**Pull request merged**
